# Generated by Django 5.1.2 on 2024-10-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nation', models.CharField(max_length=50)),
                ('pos', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('gp', models.IntegerField()),
                ('ast', models.IntegerField()),
                ('crd_Y', models.IntegerField()),
                ('crd_R', models.IntegerField()),
                ('x_G', models.DecimalField(decimal_places=2, max_digits=5)),
                ('club_name', models.CharField(max_length=100)),
            ],
        ),
    ]
