# Generated by Django 5.2.7 on 2025-10-24 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PL', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='club_name',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='team',
        ),
        migrations.RemoveField(
            model_name='team',
            name='ast',
        ),
        migrations.RemoveField(
            model_name='team',
            name='crd_R',
        ),
        migrations.RemoveField(
            model_name='team',
            name='crd_Y',
        ),
        migrations.RemoveField(
            model_name='team',
            name='gp',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pos',
        ),
        migrations.RemoveField(
            model_name='team',
            name='x_G',
        ),
        migrations.AddField(
            model_name='team',
            name='assists',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='blocks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='carries',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='dribble_attempts',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='dribbles',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='expected_assists_xag',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='expected_goals_xg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='goal_creating_actions',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='goals',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='non_penalty_xg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='pass_completion_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='passes_attempted',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='passes_completed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='penalty_shoot',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='penalty_shoot_on_goal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='position',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='progressive_carries',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='progressive_passes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='red_cards',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='shoot_on_target',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='shot_creating_actions',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='successful_dribbles',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='tackles',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='total_shoot',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='touches',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='yellow_cards',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='nation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
