# Generated by Django 5.1.3 on 2024-11-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PL', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='club_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.IntegerField()),
                ('club_description', models.TextField()),
                ('club_crest', models.ImageField(blank=True, default='nothing', upload_to='')),
            ],
        ),
    ]
