# Generated by Django 5.1.3 on 2024-11-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PL', '0002_club_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='club_info',
            name='club_stuff',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
