# Generated by Django 5.2.7 on 2025-10-24 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PL', '0002_rename_club_name_team_player_rename_name_team_team_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='carries',
        ),
        migrations.RemoveField(
            model_name='team',
            name='date',
        ),
        migrations.RemoveField(
            model_name='team',
            name='dribble_attempts',
        ),
        migrations.RemoveField(
            model_name='team',
            name='expected_assists_xag',
        ),
        migrations.RemoveField(
            model_name='team',
            name='goal_creating_actions',
        ),
        migrations.RemoveField(
            model_name='team',
            name='non_penalty_xg',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pass_completion_percent',
        ),
        migrations.RemoveField(
            model_name='team',
            name='passes_attempted',
        ),
        migrations.RemoveField(
            model_name='team',
            name='passes_completed',
        ),
        migrations.RemoveField(
            model_name='team',
            name='progressive_carries',
        ),
        migrations.RemoveField(
            model_name='team',
            name='progressive_passes',
        ),
        migrations.RemoveField(
            model_name='team',
            name='shot_creating_actions',
        ),
        migrations.RemoveField(
            model_name='team',
            name='successful_dribbles',
        ),
        migrations.AlterField(
            model_name='team',
            name='minutes',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
