# Generated by Django 5.1.3 on 2024-11-26 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PL', '0003_club_info_club_stuff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club_info',
            name='club_stuff',
        ),
    ]
