# Generated by Django 5.1.3 on 2024-11-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PL', '0004_remove_club_info_club_stuff'),
    ]

    operations = [
        migrations.AddField(
            model_name='club_info',
            name='club_name',
            field=models.CharField(default='Football F.C', max_length=100),
        ),
    ]
