# Generated by Django 5.2.7 on 2025-10-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PL', '0005_remove_team_carries_remove_team_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='club_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(default='Football F.C', max_length=100)),
                ('club_id', models.IntegerField()),
                ('club_description', models.TextField()),
                ('club_crest', models.ImageField(blank=True, default='nothing', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='soccer_buddy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='nothing', upload_to='')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
