# Generated by Django 5.1.4 on 2024-12-17 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PL', '0007_mymodel_alter_category_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='soccer_buddy',
        ),
    ]
